In [2]:
import numpy as np
a = np.random.randint(1, 10, (2,3,4,5))
print (a)

[[[[4 1 3 9 4]
   [7 5 6 3 5]
   [9 7 8 9 8]
   [6 8 8 3 9]]

  [[2 1 6 2 6]
   [7 4 2 4 1]
   [7 2 9 5 7]
   [4 2 9 1 4]]

  [[3 4 8 3 2]
   [7 1 3 6 6]
   [4 1 8 9 8]
   [8 1 9 5 7]]]


 [[[2 2 7 7 8]
   [8 5 9 6 6]
   [5 2 8 7 2]
   [5 5 7 5 5]]

  [[1 8 6 3 2]
   [9 4 5 8 4]
   [5 1 4 7 2]
   [6 3 9 3 1]]

  [[3 6 3 8 9]
   [4 7 4 2 4]
   [7 6 2 7 2]
   [1 9 7 2 7]]]]


In [3]:
np.sum(a, axis=3, keepdims = False)


array([[[21, 26, 41, 34],
        [17, 18, 30, 20],
        [20, 23, 30, 30]],

       [[26, 34, 24, 27],
        [20, 30, 19, 22],
        [29, 21, 24, 26]]])

In [10]:
b = np.random.randint(1,5, (7,8))
print (b)

[[1 3 1 3 2 3 4 2]
 [1 4 1 1 2 3 1 1]
 [4 1 2 3 3 2 4 2]
 [3 4 4 2 3 2 1 3]
 [2 3 2 3 2 2 3 4]
 [2 3 4 3 4 4 2 2]
 [2 1 4 4 1 2 2 2]]


In [6]:
import os
os.getcwd()

'C:\\Users\\jzhang2\\Documents\\GitHub\\DBScript\\Python\\Notebook'

In [11]:
np.sum(b, axis=0, keepdims = True)

array([[15, 19, 18, 19, 17, 18, 17, 16]])

In [12]:
print (b.shape)

(7, 8)
