In [46]:
import numpy as np
a = np.random.randint(-100, 100, (5120, 19, 1))

c = np.random.rand(5120, 19, 1)
d = np.append(a,c, axis = 2)

print (d.shape)

(5120, 19, 2)


In [47]:
e = np.random.rand(5120, 19, 1)
e = np.append(d,e, axis=2)
print(e.shape)

(5120, 19, 3)


In [4]:
np.sum(a, axis=3, keepdims = False)


array([[[23, 27, 15, 14],
        [33, 20, 19, 23],
        [36, 21, 23, 20]],

       [[16, 25, 19, 30],
        [37, 28, 31, 26],
        [28, 30, 23, 34]]])

In [13]:
b = np.random.randint(1,5, (2,3,2))
print (b)
print (b.shape)

[[[4 1]
  [2 1]
  [3 3]]

 [[2 4]
  [1 4]
  [1 4]]]
(2, 3, 2)


In [1]:
import os
os.getcwd()

'C:\\Users\\jzhang2\\Documents\\GitHub\\DBScript\\Python\\Notebook'

In [2]:
c = np.sum(b, axis=(0,1), keepdims = True)
print (c)
print (c.shape)

NameError: name 'np' is not defined

[[4 4 1 3 4 2 3 1]
 [4 2 3 1 4 2 4 1]
 [2 4 3 4 1 1 3 1]
 [3 2 4 2 4 3 4 4]
 [2 1 4 2 4 1 1 1]
 [2 4 1 3 1 1 1 3]
 [4 4 4 2 4 1 1 1]]
(7, 8)
